name: user_repository
description: The repo that handles users
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  get_it: ^7.7.0
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  json_annotation: ^4.9.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0

  build_runner: ^2.4.9

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true