name: checklist_to_do
description: "Checklist To Do is a convenient mobile application for creating checklists and tracking the completion of tasks"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  json_annotation: ^4.9.0
  auto_route: ^8.1.3
  shared_preferences: ^2.2.2
  image_cropper: ^6.0.0
  image_picker: ^1.0.8
  path: ^1.8.0

  cupertino_icons: ^1.0.8

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0

  build_runner: ^2.4.10

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
